### ISSUE TITLE
How to configure this?

### ISSUE THREAD

**Issue by Qonstrukt** [egguy/grott-home-assistant-add-on#17]
There's no documentation on the values that need to be put in the `mqtt` field.
I've made my ShineLink-X connect to this add-on, and I can see it's working because it says a client is connected in the log, but no extra devices or entities are showing up under my MQTT integration in HA.
I'm already using MQTT for a couple of other things, so I know it's working.

The log also shows this, which seems to indicate it has no idea how to connect:
```
_Extension:
	extension:          	 True
	extname:            	 grott_ha
	extvar:             	 {'ha_mqtt_host': '', 'ha_mqtt_port': '', 'ha_mqtt_user': '', 'ha_mqtt_password': ''}
```

Edit:
Looking through the code, it seems pretty obvious that this only works with the Add-on MQTT server, but I use my own external one.

Also the current version does have the configuration fields to set `extvar` for example, but the `script.sh` file never takes those into account.

**Comment by egguy** [comment]
Yes, at the moment there is no configuration for a custom MQTT server. I will try to add this soon.

**Comment by Qonstrukt** [comment]
No, not currently. I've already have it running in a separate container now, but I had to do some searching branches to find the correct latest version of your HA extension, which is really nice. 🙂 
Maybe a good idea to at least add some basic documentation on what it can do and can't to prevent more questions. And a link to your latest HA extension script, because the work is greatly appreciated!

**Comment by DominikWrobel** [comment]
I've installed your addonn today, I have two growatt inverters. But how do I get the data to mqtt? No new entities show up. I have MQTT configured already in HA

**Comment by egguy** [comment]
Hi, you need to follow the grott tutorial on how to reroute the traffic to the HA IP: https://github.com/johanmeijer/grott/wiki/Rerouting-Growatt-Wifi-TCPIP-data-via-your-Grott-Server

**Comment by egguy** [comment]
@Qonstrukt I found a good way to add this functionality, I will probably do this next week. I don't have a computer at the moment. 

Do you have any suggestions of what I can add to the documentation?

**Comment by egguy** [comment]
Hi @Qonstrukt,

I've updated the add-on to allow configuring a custom MQTT broker.

**Comment by Qonstrukt** [comment]
Great job, also on the expanded documentation!

**Comment by egguy** [comment]
All thanks To zigbee2mqtt from where i stole a bunch of code :pirate_flag:
