### ISSUE TITLE
Update a json layout file

### ISSUE THREAD

**Issue by BarmanMaz** [egguy/grott-home-assistant-add-on#24]
Hi,
I'm running the addon you generated but i'm strugling to update as reqested.
can you please help me? I have try to follow the istruction from Johan but these goes to much deep into my knoledge

How i can put the json file into di main directory

**"" 
Can you please put the layout file t06221b.json form the examples library in your grott main directory?

See:
https://github.com/johanmeijer/grott/blob/Beta-(2.8.x)/examples/Record%20Layout/T06221b.json

If everything works right this will process your SDM630 records and generate MQTT messages for this. Can you very form the log if this what you expected.

I think we have to do some additional work to get this information in HA with the plugin/extension. @egguy can you please help with this?**
""

Many thanks

**Comment by egguy** [comment]
Hello, sorry for the late response.

The add-on mounts the folder `/conf/grott`. You can add a grott.ini config and add a JSON file inside.

You can use the editor add-on for this or the VS Code add-on.
