### ISSUE TITLE
pdischarge1 wrong unit (SPH) (edge release)

### ISSUE THREAD

**Issue by benhumphry** [egguy/grott-home-assistant-add-on#26]
Hi

Looking at the MQTT config for pdischarge1, I see
`  "state_class": "total",
  "device_class": "energy",
  "unit_of_measurement": "kWh",` 

I think this should be (as with p1charge1): 
`  "state_class": "measurement",
  "device_class": "power",
  "unit_of_measurement": "W",`

**Comment by egguy** [comment]
The change is published in the new edge version.
