### ISSUE TITLE
Load consumption today - wrong unit of measurement (SPH)

### ISSUE THREAD

**Issue by benhumphry** [egguy/grott-home-assistant-add-on#28]
Hi

Current unit of measurement for **load consumption today** parameter (on my SPH) is:
`"unit_of_measurement": "Wh"`

I believe this should be: 
`"unit_of_measurement": "kWh"`

**Comment by egguy** [comment]
Thanks for the report. I will investigate.

**Comment by egguy** [comment]
The problem has been addressed in the commit: https://github.com/egguy/grott/commit/46be16a96e9a99fe6ccfa7b707cf1c4fae35cf1c
