### ISSUE TITLE
just stopped working 

### ISSUE THREAD

**Issue by chirs-51** [egguy/grott-home-assistant-add-on#30]
the server has been running in monts with only frew errores and then just needed a reboot. 

but now its just do not work just stopped no reel info from the log. end no restart and no updates wars done before the brake of grott.

i need to say i have both of the integrations from you and another way to install it to get the sever version but non off them is working no data on the mqtt and no data to growatt sever. 

settings
data_path: /config/grott
gmode: proxy
gnomqtt: true
ginvtype: default
ginvtypemap: "{\"OMCMA3800G\":\"sph\"}"
retain: false
verbose: false
mqtt: {}
gmqttinverterintopic: true

log 

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[20:36:50] INFO: Preparing to start...
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Grott Growatt logging monitor : 2.7.8
Grott process configuration file
Grott process environmental variables
	Pulled 'ginvtype=default' from the environment
	Pulled 'ginvtypemap={"OMCMA3800G":"sph"}' from the environment
	Pulled 'gnomqtt=true' from the environment
	Pulled 'gextension=True' from the environment
	Pulled 'gextname=grott_ha' from the environment
	Pulled 'gextvar={"ha_mqtt_host": "core-mosquitto", "ha_mqtt_port": "1883", "ha_mqtt_user": "addons", "ha_mqtt_password": "iepu4Paizael1ievooW5loth4Ahph7aiVaethuihooghaed5ko1RoocayiequahH", "ha_mqtt_retain": False}' from the environment
Grott override settings if set in commandline
Grott process json layout files
Grott proxy mode started
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Hostname : 8ce4abae-grott-current
IP :  172.30.33.7 , port :  5279 
	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.7', 42150), raddr=('47.91.67.66', 5279)>
	 - Growatt packet received:
		  <socket.socket fd=6, family=2, type=1, proto=0, laddr=('172.30.33.7', 42152), raddr=('47.91.67.66', 5279)>
	 - Growatt packet received:
		  <socket.socket fd=8, family=2, type=1, proto=0, laddr=('172.30.33.7', 42168), raddr=('47.91.67.66', 5279)>

**Comment by chirs-51** [comment]
just to add i updated home assistant after grott broke drown in hops for a fix :/

**Comment by chirs-51** [comment]
damm after 5-6 hours its startede do Work again

**Comment by Petorrr** [comment]
Same here, but now it is down again. Looks like the Growatt server has a problem, the Shinephoneapp and Growatt server also shows data logging stopped this afternoon for 6 hours, then some logs again, and now stopped again. I thought the HA Grott logger would work independent of the Growatt server, but apparently the data loggers stop working also when the Growatt server is not functioning properly?

**Comment by pi4lab** [comment]
Same here too....

**Comment by gajotnt** [comment]
The dev of Grott made this comment.

https://github.com/johanmeijer/grott/issues/347#issuecomment-1583221748

Maybe @egguy can include this in the addon?

**Comment by daath** [comment]
5 hours and 10 minutes after it went down, it has come up for me as well ...

![image](https://github.com/egguy/grott-home-assistant-add-on/assets/543124/0fdaafce-10de-4f98-ab3c-f0d49e3341bd)

Bit of a gap in data ;P

**Comment by daath** [comment]
> PS: if you know a way to inject the data without low-level SQL shenanigans, I'm genuinely interested.

Check out Spook: https://github.com/frenck/spook
It has: 

Service: Import statistics
Call it using: [recorder.import_statistics](https://my.home-assistant.io/redirect/developer_call_service/?service=recorder.import_statistics)

Advanced service to directly inject historical statistics data into the recorder long-term stats database. #easy

**Comment by egguy** [comment]
@daath Seems dangerous. I like it :D
