### ISSUE TITLE
Double Devices

### ISSUE THREAD

**Issue by rolfbe** [egguy/grott-home-assistant-add-on#31]
I have a problem with the add on. The installation went smoothly and the system quickly recognized the device with the code associated with the inverter (CS12345678). The next day when booting the inverter, a new device was recognized via MQTT with the serial XXXXXXXXXXXX.

Now it seems that each day (and sometimes it switches during the day) that the data is pushed to the MQTT of CS12345678 or to the XXXXXXXXXX. This makes it difficult to set up the dashboard properly.

I do not know if this is a (known) problem of the add on, or if it is due to the Growatt data logger. 

I am using the following version:
Home Assistant 2023.6.1 
Supervisor 2023.06.2 
Operating System 10.2

Growatt Wifi: WL-WF stick

I'm not very good at programming, so hopefully someone can point me in the right direction.

![tempsnip](https://github.com/egguy/grott-home-assistant-add-on/assets/49622053/b4292366-8520-454c-a46a-37242124e38a)

**Comment by egguy** [comment]
O_o that's a weird one. 
I tried to take a look at the grott source code but didn't see anything related to XXXXXXXXXXXX.
As for the extension, it doesn't do any treatment on serial number (just use it to do the declaration).

I will keep an eye on this.

You can dump the data sent by grott / addon by going to the configuration of the MQTT extension in HA. Then you can select to listen to the message. The subject is: `homeassistant/grott/#`

You can look if you receive some XXXXXX serial number.
