### ISSUE TITLE
Port Problem

### ISSUE THREAD

**Issue by Bausenhagener** [egguy/grott-home-assistant-add-on#32]
Hi, 

i have some trouble by starting the Add-ons. "Grott - HA extension" starts with no problems. Trying to start ".Grott edge generated an error message, that port 5279 is allready in use. I assume that the ports shouldn't be changed, should they?

Thanks

**Comment by egguy** [comment]
Hello,

There are two ports you can change.

- The grott port, thought configuration
- The add-on port

I advise not to touch the first. In the case of an add-on, there is a fixed port where the data is forwarded (in this case 5279). If you change the grott listening port, and put for example 2000, the data will still be forwarded to 5279 in the container.

But you can keep the default port in grott, and change the port used by the add-on to forward the data to grott. You can find this setting in `Configuration -> Network` at the bottom:

![image](https://github.com/egguy/grott-home-assistant-add-on/assets/186777/2f325999-5483-4346-a9f0-899c7ae76f17)
