### ISSUE TITLE
Changes in Home Assistant 2024.2.0 Requires new Device-Names

### ISSUE THREAD

**Issue by HaareistNase** [egguy/grott-home-assistant-add-on#37]
Its seems like HA will Change some naming rules which affect Grott.
But Im to dump to understand what I can do in this case. 
Or do you have to change something in your wonderfull working addon?

![grafik](https://github.com/egguy/grott-home-assistant-add-on/assets/135537446/90473251-9be7-4f1f-8548-6c8bcb01bbcb)

**Comment by chesterflaps** [comment]
I've literally just followed the steps to get this up and running and after reboot, I get the same message

**Comment by egguy** [comment]
Hi,
It created a fix for grott_ha. I will publish soon a new add-on.

**Comment by chesterflaps** [comment]
> Hi, It created a fix for grott_ha. I will publish soon a new add-on.

Is this what has caused my Grott to stop working?

there was an update on HA so I installed it and now Grott stops as soon as I start it

**Comment by Maes152** [comment]
Has this issue been resolved? I saw an update come through for the addon but can't find any recent code changes that would imply it has been fixed.
Holding out on updating home assistant until this is fixed.

**Comment by egguy** [comment]
Yes, this contains the updated grott ha add-on. I'm currently updating the repository to have a more proper release process.
