### ISSUE TITLE
Grott add on stops after starting

### ISSUE THREAD

**Issue by chesterflaps** [egguy/grott-home-assistant-add-on#40]
Hi all.

Every time I start the Gott edge add on, it stops almost immediately and all of the entities for the PV, say unkown for the values.

**Comment by egguy** [comment]
hi, 
Can you activate the debug mode and look at the logs? This behaviour, can also come from a malformed config line.

**Comment by chesterflaps** [comment]
After alot of messing about, I got it working. Couldn't tell you how though other than possibly due to 2 different versions of Grott
