### ISSUE TITLE
Grott parsing data from growatt into MQTT message, but sensors not populating in home assistant

### ISSUE THREAD

**Issue by splynch** [egguy/grott-home-assistant-add-on#47]
I am running the grott home assistant addon, and grott (after a problem with inverter types) appears to be parsing all data properly, and puts that into an MQTT message, but not all appears as sensors in Home assistant.  

An MQTT message that I see from Grott is:
MQTT jsonmsg:
{"device": "KSM0CLK03Z", "time": "2023-08-15T08:46:58", "buffered": "no",
"values": {"datalogserial": "XGD6DBH3CU", "pvserial": "KSM0CLK03Z",
"pvstatus": 5, "pvpowerin": 8000, "pv1voltage": 2508, "pv1current": 31,
"pv1watt": 8024, "pv2voltage": 0, "pv2current": 0, "pv2watt": 0,
"pvpowerout": 4144, "pvfrequentie": 4995, "pvgridvoltage": 2475,
"pvgridcurrent": 17, "pvgridpower": 4251, "pvgridvoltage2": 0,
"pvgridcurrent2": 0, "pvgridpower2": 0, "pvgridvoltage3": 0,
"pvgridcurrent3": 0, "pvgridpower3": 0, "totworktime": 4606732, "eactoday":
3, "pvenergytoday": 3, "eactotal": 1698, "epvtotal": 1904, "epv1today": 4,
"epv1total": 1877, "epv2today": 0, "epv2total": 0, "pvtemperature": 353,
"pvipmtemperature": 316, "pvboosttemp": 334, "bat_dsp": 519,
"eacharge_today": 2, "eacharge_total": 115, "batterytype": 1,
"uwsysworkmode": 5, "systemfaultword0": 0, "systemfaultword1": 0,
"systemfaultword2": 0, "systemfaultword3": 0, "systemfaultword4": 0,
"systemfaultword5": 0, "systemfaultword6": 0, "systemfaultword7": 2048,
"pdischarge1": 0, "p1charge1": 3200, "vbat": 517, "SOC": 11, "pactouserr":
0, "pactousertot": 0, "pactogridr": 0, "pactogridtot": 0, "plocaloadr":
4800, "plocaloadtot": 4800, "spdspstatus": 5, "spbusvolt": 3109,
"etouser_tod": 46, "etouser_tot": 2484, "etogrid_tod": 1, "etogrid_tot": 25,
"edischarge1_tod": 2, "edischarge1_tot": 671, "eharge1_tod": 0,
"eharge1_tot": 507, "elocalload_tod": 53, "elocalload_tot": 4527}}

but the sensors I see are:

![260658924-09c37548-feb5-4b42-86fb-7f807b24f476](https://github.com/egguy/grott-home-assistant-add-on/assets/66905800/5fb70e51-0fb6-4180-b9f5-be3a91e4e6ee)
![260658924-09c37548-feb5-4b42-86fb-7f807b24f476](https://github.com/egguy/grott-home-assistant-add-on/assets/66905800/81273a66-1db6-4552-b1c9-3c504f2c2da1)

The main ones missing are:
Total solar generation: epv1total [X/10]kwh
Total amount battery charged: eharge1_tot [x/10]kwh
total amount discharged from battery: edischarge1_tot [x/10]kwh
state of charge on battery: SOC [x]%

Is there a configuration option I need to enable more sensors? Looking at the sensors configuration code, it looks like it should be finding, for example, EPV1total, but its not currently. Or maybe the code in github hasn't made it to production yet?

Many thanks

**Comment by f0m3** [comment]
I have a similar problem. My log says:
```
- MQTT jsonmsg: 
			 {"device": "XX", "time": "2023-08-30T22:04:57", "buffered": "no",
			 "values": {"datalogserial": "XX", "pvserial": "XX",
			 "pvstatus": 6, "pvpowerin": 0, "pv1voltage": 0, "pv1current": 0, "pv1watt":
			 0, "pv2voltage": 0, "pv2current": 0, "pv2watt": 0, "pvpowerout": 0,
			 "pvfrequentie": 4997, "pvgridvoltage": 4137, "pvgridcurrent": 6,
			 "pvgridpower": 3749, "pvgridvoltage2": 4180, "pvgridcurrent2": 5,
			 "pvgridpower2": 0, "pvgridvoltage3": 3982, "pvgridcurrent3": 6,
			 "pvgridpower3": 0, "totworktime": 111714063, "eactoday": 122,
			 "pvenergytoday": 122, "eactotal": 108440, "epvtotal": 123949, "epv1today":
			 50, "epv1total": 42268, "epv2today": 103, "epv2total": 81681,
			 "pvtemperature": 280, "pvipmtemperature": 261, "pvboosttemp": 259,
			 "bat_dsp": 2074, "eacharge_today": 13, "eacharge_total": 11329,
			 "batterytype": 1, "uwsysworkmode": 6, "systemfaultword0": 0,
			 "systemfaultword1": 0, "systemfaultword2": 0, "systemfaultword3": 0,
			 "systemfaultword4": 32, "systemfaultword5": 0, "systemfaultword6": 0,
			 "systemfaultword7": 2048, "pdischarge1": 0, "p1charge1": 0, "vbat": 2068,
			 "SOC": 10, "pactouserr": 9000, "pactousertot": 9000, "pactogridr": 0,
			 "pactogridtot": 0, "plocaloadr": 9000, "plocaloadtot": 9000, "spdspstatus":
			 6, "spbusvolt": 6498, "etouser_tod": 130, "etouser_tot": 78615,
			 "etogrid_tod": 3, "etogrid_tot": 32501, "edischarge1_tod": 57,
			 "edischarge1_tot": 37902, "eharge1_tod": 66, "eharge1_tot": 39048,
			 "elocalload_tod": 269, "elocalload_tot": 168993}}
	 - Grott MQTT topic used : energy/growatt
	 - MQTT message message sent
```

but only this appears in the entities in ha:
![image](https://github.com/egguy/grott-home-assistant-add-on/assets/2865943/60da7cfa-b6d8-4618-a549-46e24cf0d86f)

**Comment by vvv850** [comment]
Same issue here:
```
MQTT:
'datalogserial': {'value': 16, 'length': 10, 'type': 'text', 'incl': 'yes'
'pvserial': {'value': 36, 'length': 10, 'type': 'text'
'date': {'value': 56, 'divide': 10
'recortype1': {'value': 70, 'length': 2, 'type': 'num', 'incl': 'no'
'recortype2': {'value': 74, 'length': 2, 'type': 'num', 'incl': 'no'
'pvstatus': {'value': 78, 'length': 2, 'type': 'num'
'pvpowerin': {'value': 82, 'length': 4, 'type': 'num', 'divide': 10
'pv1voltage': {'value': 90, 'length': 2, 'type': 'num', 'divide': 10
'pv1current': {'value': 94, 'length': 2, 'type': 'num', 'divide': 10
'pv1watt': {'value': 98, 'length': 4, 'type': 'num', 'divide': 10
'pv2voltage': {'value': 106, 'length': 2, 'type': 'num', 'divide': 10
'pv2current': {'value': 110, 'length': 2, 'type': 'num', 'divide': 10
'pv2watt': {'value': 114, 'length': 4, 'type': 'num', 'divide': 10
'pvpowerout': {'value': 122, 'length': 4, 'type': 'numx', 'divide': 10
'pvfrequentie': {'value': 130, 'length': 2, 'type': 'num', 'divide': 100
'pvgridvoltage': {'value': 134, 'length': 2, 'type': 'num', 'divide': 10
'pvgridcurrent': {'value': 138, 'length': 2, 'type': 'num', 'divide': 10
'pvgridpower': {'value': 142, 'length': 4, 'type': 'num', 'divide': 10
'pvgridvoltage2': {'value': 150, 'length': 2, 'type': 'num', 'divide': 10
'pvgridcurrent2': {'value': 154, 'length': 2, 'type': 'num', 'divide': 10
'pvgridpower2': {'value': 158, 'length': 4, 'type': 'num', 'divide': 10
'pvgridvoltage3': {'value': 166, 'length': 2, 'type': 'num', 'divide': 10
'pvgridcurrent3': {'value': 170, 'length': 2, 'type': 'num', 'divide': 10
'pvgridpower3': {'value': 174, 'length': 4, 'type': 'num', 'divide': 10
'pvenergytoday': {'value': 182, 'length': 4, 'type': 'num', 'divide': 10
'pvenergytotal': {'value': 190, 'length': 4, 'type': 'num', 'divide': 10
'totworktime': {'value': 198, 'length': 4, 'type': 'num', 'divide': 7200
'pvtemperature': {'value': 206, 'length': 2, 'type': 'num', 'divide': 10
'isof': {'value': 210, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'gfcif': {'value': 214, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'dcif': {'value': 218, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'vpvfault': {'value': 222, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'vacfault': {'value': 226, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'facfault': {'value': 230, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'tmpfault': {'value': 234, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'faultcode': {'value': 238, 'length': 2, 'type': 'num', 'divide': 1, 'incl': 'no'
'pvipmtemperature': {'value': 242, 'length': 2, 'type': 'num', 'divide': 10
'pbusvolt': {'value': 246, 'length': 2, 'type': 'num', 'divide': 10, 'incl': 'no'
'nbusvolt': {'value': 250, 'length': 2, 'type': 'num', 'divide': 10, 'incl': 'no'
'epv1today': {'value': 278, 'length': 4, 'type': 'num', 'divide': 10
'epv1total': {'value': 286, 'length': 4, 'type': 'num', 'divide': 10
'epv2today': {'value': 294, 'length': 4, 'type': 'num', 'divide': 10
'epv2total': {'value': 302, 'length': 4, 'type': 'num', 'divide': 10
'epvtotal': {'value': 310, 'length': 4, 'type': 'num', 'divide': 10
'rac': {'value': 318, 'length': 4, 'type': 'num', 'divide': 1, 'incl': 'no'
'eractoday': {'value': 326, 'length': 4, 'type': 'num', 'divide': 1, 'incl': 'no'
'eractotal': {'value': 334, 'length': 4, 'type': 'num', 'divide': 1, 'incl': 'no'}}
```

And sensors in HA:
```
Datalogger serial
xxxxxxxxxxxx
Generated energy (Today)
19.1 kWh
Generated energy (Total)
329.4 kWh
Grid Frequency
49.96 Hz
Grott last data push
3 minutes ago
Intelligent Power Management temperature
55.7 °C
Inverter boost temperature
53.0 °C
Inverter temperature
72.6 °C
Lifetime solar energy
301.3 kWh
nbusvolt
3161.0
pbusvolt
3093.0
Phase 1 current
9.1 A
Phase 1 power
2,104.8 W
Phase 1 voltage
231.3 V
Phase 2 current
9.1 A
Phase 2 power
2,085.7 W
Phase 2 voltage
229.2 V
Phase 3 current
9.1 A
Phase 3 power
2,183.0 W
Phase 3 voltage
239.9 V
PV Input (Actual)
6,575.0 W
PV Output (Actual)
6,476.4 W
PV1 Current
11.0 A
PV1 Voltage
376.0 V
PV1 Watt
4,136.0 W
PV2 Current
6.9 A
PV2 Voltage
333.1 V
PV2 Watt
2,298.3 W
serial
XXXXXXXXXX
Solar PV1 energy today
10.4 kWh
Solar PV1 production (Total)
192.1 kWh
Solar PV2 energy today
7.3 kWh
Solar PV2 production (Total)
109.2 kWh
State
1.0
uwBatVolt_DSP
0.0
Vac_RS
403.3
Vac_ST
402.9
Vac_TR
406.5
Working time
98:22:05
```

I basically cannot see what is exported and imported from grid.

**Comment by soscomo** [comment]
Same problem, y want to see exported to grid to use in energy panel.

**Comment by doenau** [comment]
Likewise, I am not seeing any export or consumption values.
I have attempted to configure the inverter type, but that results in even less meaningful information (TLX gives nothing but errors, SPH gives some data but values are incorrect (or in the incorrect positions), so it is currently set as 'default'.
My inverter is a MIN-1000TL-X with Shine Stick and ShineLAN box.
Current config is:

`data_path: /config/grott
gmode: proxy
grott_mqtt: true
ginvtype: default
ginvtypemap: ""
retain: true
verbose: true
ha_plugin: true
mqtt: {}
gmqttpassword: xxxxx
gmqtttopic: energy/grott
gmqttuser: xxxxx
gdecrypt: false`

![image](https://github.com/egguy/grott-home-assistant-add-on/assets/112148640/8983d3b9-5753-428a-ae1b-3b14a27594b8)

**Comment by splynch** [comment]
For those having the same problem, I realised i was on the stable branch. Switching to the edge plugin mostly resolved my issues. There are a few sensors missing, but i've been getting by without them. 

Are the others having this issue on the edge version?

**Comment by doenau** [comment]
> For those having the same problem, I realised i was on the stable branch. Switching to the edge plugin mostly resolved my issues. There are a few sensors missing, but i've been getting by without them.
> 
> Are the others having this issue on the edge version?

I could only get the Edge version working. Even with the stable version using the same configuration parameters, I got nothing from it. It wasn't deciding the data.
I updated both add-ons, but though they are different versions, they are both now named as 'grott' and both say they are Edge versions. They both also shows as "production ready". :|
Anyway - the one I have partial working is the b6f2f24 version. 044729b  doesn't give me any data (as mentioned previously).
[grott.txt](https://github.com/egguy/grott-home-assistant-add-on/files/12864776/grott.txt)
My latest log is attached FYI.

**Comment by egguy** [comment]
Sorry for the confusion at the moment.
I'm reworking the packaging to make it easier to maintain, document and update the changelog.

I will probably remove the edge soon and have grott based on the 2.7 and grott-beta with the 2.8 version.

I'm trying to push the changes as fast as possible, but I also have some things to deal before.

In the meantime I recommend you to use the edge version, it's based on the stable addon and grott (2.7)

**Comment by doenau** [comment]
> Sorry for the confusion at the moment. I'm reworking the packaging to make it easier to maintain, document and update the changelog.
> 
> I will probably remove the edge soon and have grott based on the 2.7 and grott-beta with the 2.8 version.
> 
> I'm trying to push the changes as fast as possible, but I also have some things to deal before.
> 
> In the meantime I recommend you to use the edge version, it's based on the stable addon and grott (2.7)

Thanks for the reply, and your efforts on this (and others).

1. Just confirming (based on my explanation above), build b6f2f24 is the Edge version you recommend?
2. Are the issues described (and the provided logs) suggesting that the inverter/datalogger model, format/layout is not currently supported, or perhaps leaning more to my own config issue?
I'm not pressing for a full response or resolution, just curious for your initial thoughts in the meantime.
Thanks again.

**Comment by doenau** [comment]
> 1. Yes, The edge is mostly the stable version at the moment
> 2. So you have a MIN inverter, it seems the support has been committed in the 2.8 branch: https://github.com/johanmeijer/grott/tree/Beta-(2.8.x)#new-in-version-28
> 
> You can use my edge (real edge this time) repo: https://github.com/egguy/ha-addons-edge/ as a source. The beta version as indicated is the 2.8 branch with the min inverter support. This repository will be the edge version when I will finish repackaging the add-on (there will probably a dev repo at a later date)
> 
> You will need to add `min` to the inverter type configuration.

**Thanks for this.** I have run up the beta as a local add-on and it's giving me mostly what I want (I think) :)
Some of the parameters are a little confusing (maybe its just me) and I needed to customize a number of sensors to add the device_class etc.
This will get me going for now thoug, thank you.
If you want more info for debugging/integration of the inverter type, feel free to let me know.
On a side note... it brought through a number of unnecessary sensors (battery sensors for example) - it would be handy to have a configuration setting during setup to disable (ie: never include) Battery/Charger sensors, which would save users from having to manually disable 20+ sensors.

**Comment by egguy** [comment]
Hi, I would be interested to see the modifications you have done. If there is some tuning or modification of the name of the sensors.

**Comment by doenau** [comment]
> Hi, I would be interested to see the modifications you have done. If there is some tuning or modification of the name of the sensors.

In the beta that I ran up as a local add-on, it didn't seem to have any device class and state class configurations, so I had to add them to my configuration.yaml > 'customize' section, so that I could use them in the Energy dashboard (See below)
I am not using Grott Beta branch (2.8) v0.1.5 and still need to use the customize configuration.

```
customize:
    sensor.bsk5cdh05c_etogridtotal:
      state_class: total_increasing
      device_class: energy
      unit_of_measurement: kWh
    sensor.bsk5cdh05c_eloadtotal:
      state_class: total_increasing
      device_class: energy
      unit_of_measurement: Wh
    sensor.bsk5cdh05c_etogridtoday:
      state_class: total_increasing
      device_class: energy
      unit_of_measurement: kWh
    sensor.bsk5cdh05c_eloadtoday:
      state_class: total
      device_class: energy
      unit_of_measurement: kWh
    sensor.bsk5cdh05c_ptogridtotal:
      state_class: total
      device_class: energy
      unit_of_measurement: kWh
    sensor.bsk5cdh05c_ptoloadtotal:
      state_class: total
      device_class: energy
      unit_of_measurement: kWh
```

If I do not use the Customise feature, then I get this issue and cannot use them in the Energy Dashboard:
![image](https://github.com/egguy/grott-home-assistant-add-on/assets/112148640/1069db7a-1d6e-45bf-92b3-3857c627027b)

**Comment by egguy** [comment]
Ho, thanks, those measures seem to have been missed from my plugin.
 I base the sensors on the 2.7 branch but it seems there is some new one.

 I will update in the next iteration probably, You can see the progress here: https://github.com/egguy/grott-ha-plugin/issues/10
