### ISSUE TITLE
How to install in Home Assistan Docker

### ISSUE THREAD

**Issue by gdcomunale** [egguy/grott-home-assistant-add-on#48]
Hello,
this is a great plugin!!!

Can you please instruct me on how to install this plugin on a Home Assistant docker installation I have on my RPI4?

Thanks in advance.

D.

**Comment by egguy** [comment]
Hello,

This add-on only works with haaos. I never tested it in docker. If there is a way, I will add this to the documentation.

You can use a docker build (from the official grott) to use this extension.
