### ISSUE TITLE
Pv Output only updating every 10 minutes

### ISSUE THREAD

**Issue by kineci** [egguy/grott-home-assistant-add-on#49]
I'm only receiving output data every 10 minutes, which is quite slow. Therefore, I conducted some research on how to increase the scan interval to achieve better data resolution. During my investigation, I came across issue #35 , where a user reported receiving data every minute, stating, "PV_out_actual in Watts is OK and refreshing every minute."

This leads me to believe that I may have misconfigured something. But where could the issue be?

Protocol:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[17:22:35] INFO: Preparing to start...
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Grott Growatt logging monitor : 2.7.8
Grott process configuration file
Grott process environmental variables
	Pulled 'ginvtype=default' from the environment
	Pulled 'gnomqtt=True' from the environment
	Pulled 'gextension=True' from the environment
	Pulled 'gextname=grott_ha' from the environment
	Pulled 'gextvar={"ha_mqtt_host": "core-mosquitto", "ha_mqtt_port": "1883", "ha_mqtt_user": "addons", "ha_mqtt_password": "vaingaephei4oorobei5deeSha7ayoX5OjaeL9aisahQuuethuPeiQuai8efusha", "ha_mqtt_retain": False}' from the environment
Grott override settings if set in commandline
Grott process json layout files
Grott proxy mode started
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Hostname : 8ce4abae-grott-current
IP :  172.30.33.3 , port :  5279

**Comment by egguy** [comment]
Hi, regarding to this issue, the scan interval depend on the configuration of the stick.

If you go to grott, you can probably find the change in the wiki: https://github.com/johanmeijer/grott/
