### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by GeraldPape** [egguy/grott-home-assistant-add-on#54]
![image](https://github.com/egguy/grott-home-assistant-add-on/assets/72608781/e29ea133-6f74-403c-a7e4-d6c3f02d231e)

Summing up PV1 and PV2 gives 22,4
Generated energy shows only 14,7
![image](https://github.com/egguy/grott-home-assistant-add-on/assets/72608781/7cbd96c1-dd79-40e3-95f4-ff0d1736d540)

Why?

Btw. Shine cloud shows correct value, pvoutput also received wrong summation

**Comment by egguy** [comment]
I need to take a look, but the addon+extension is only relaying the information decrypted by grott. This can be either a bad decoding or the values, or a bad report from the inverter.

As a workaround, you can use the `settings -> devices -> helper` and create a sum of the two sensors to have the correct value.

**Comment by martijntonies** [comment]
Could be a record decoding error like I think I have?
https://github.com/johanmeijer/grott/issues/443

**Comment by GeraldPape** [comment]
Checked on the Growatt Cloud - Values are summing up correctly:
![grafik](https://github.com/egguy/grott-home-assistant-add-on/assets/72608781/2a17d76f-98b5-4fcd-a071-49e5c65e35c7)

so seems to be some decoding issue?

**Comment by egguy** [comment]
I will find if there is a decoding error. Perhaps it’s an invalid register.
Meanwhile, you can use a home assistant helper to generate the sum of the 2 sensors. 

You can use this likg to go to: [Settings > Devices & Services > Helpers](https://my.home-assistant.io/redirect/helpers) and click the add button at the bottom right. There is a "combine sensors" and then you can do a sum
