### ISSUE TITLE
Not seeing export and load consumption, only PV generation info

### ISSUE THREAD

**Issue by doenau** [egguy/grott-home-assistant-add-on#60]
I just switched over to the Grott add-on due to the HA Growatt integration no longer working and this being the recommended approach.
I've got both Grott (b6f2f24) and Grott - HA Extension (2.7.8) installed - noting that it won't let me update to bd5c208.

This is the result when running the HA Extension, so for the moment, I have given up on that option and it is turned off.
![image](https://github.com/egguy/grott-home-assistant-add-on/assets/112148640/6af5346a-5670-4a6e-9880-a40f30fb6439)

So, running Grott b6f2f24, I don't seem to get any EXPORT values, which I did with the Growatt integration.
I have the ShineStick connecting back via the ShineLAN box.

Is this normal, and this add-on is just lacking the export detail? Or have I done something wrong?

![image](https://github.com/egguy/grott-home-assistant-add-on/assets/112148640/2415791d-903b-434b-bd0a-94a3e4a7aead)

**Comment by Neflardio** [comment]
Missing the inverter type configuration might be the issue.
![image](https://github.com/egguy/grott-home-assistant-add-on/assets/13015114/2096adbd-4452-4abd-9076-7c112105eb95)

If that's not the issue, posting the the log  when running in verbose mode is a good starting point.

**Comment by doenau** [comment]
Thanks @Neflardio - I have tried the inverter type options and they give me worse results, either nothing, or a bunch of invalid values in all the wrong places.
anyway - for now I will close this as a duplicate, and follow issue #47 that I just found, which seems much the same.
https://github.com/egguy/grott-home-assistant-add-on/issues/47
