### ISSUE TITLE
Unable to install grott-stable after uninstall

### ISSUE THREAD

**Issue by Geo-Ron** [egguy/grott-home-assistant-add-on#63]
After a uninstall, I am unable to reinstall the addon.

![image](https://github.com/egguy/grott-home-assistant-add-on/assets/23144316/ca24402d-ae7f-4ed6-abc6-14d2cd4f7ffc)

Supervisor log:
```
23-10-11 20:45:49 ERROR (MainThread) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
23-10-11 20:46:41 ERROR (MainThread) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
23-10-11 20:48:38 ERROR (MainThread) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
23-10-11 20:50:19 ERROR (MainThread) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
```

HomeAssistant:
```
Home Assistant 2023.10.1
Supervisor 2023.10.0
Operating System 10.5
Frontend-versie: 20231005.0 - latest
```

Edge version installs fine. Using this one for now...

I was investigating an issue where the addon does not log to mosquitto...

**Comment by egguy** [comment]
Hi,
I think I see the bug, this comes from a packaging error. It should be corrected soon.

**Comment by egguy** [comment]
I think the problem should have been solved. Could you confirm?

**Comment by Geo-Ron** [comment]
I can not confirm.
Error message is the same.
As is the change number on the top right (044729b) I think.

I will check again this evening.

**Comment by Geo-Ron** [comment]
![Screenshot_20231012_122138_Home Assistant](https://github.com/egguy/grott-home-assistant-add-on/assets/23144316/118c3aa7-d98b-4384-8e7d-6bd07b436b4f)

Verifiëren! I can confirm it is ok!
Thanks
