### ISSUE TITLE
Cannot install add-on

### ISSUE THREAD

**Issue by ErikT80** [egguy/grott-home-assistant-add-on#7]
When trying to install the add-on I get the following message:

The command '/bin/ash -o pipefail -c curl -Lk 'https://github.com/johanmeijer/grott/archive/refs/heads/2.7-(Beta).zip' --output files.zip && unzip -o files.zip && rm files.zip && mv grott-*/*.py ./' returned a non-zero code: 1

Is it because of the newest grott version?

**Comment by egguy** [comment]
Hi,
Thanks for the information. I've updated the dockerbuild.

I'm currently adding the support for building images and tests to prevent this problem.
