### ISSUE TITLE
What Inverter type should I specify for Growatt MIN 10000TL-X

### ISSUE THREAD

**Issue by LightMoon** [egguy/grott-home-assistant-add-on#75]
Hi,

I am not sure what inverter type should I specify in grott.ini for Growatt MIN 10000TL-X ?
Datasheet - https://www.austraenergy.com.au/wp-content/uploads/2021/08/MIN-700010000-TL-X.pdf

```
# Specify the type of the inverter (default/sph/spf/max)
invtype = ?
```

**Comment by LightMoon** [comment]
It would be good if you could edit the documentation with something like this 
MIN 2500-**10000**TL

**Comment by egguy** [comment]
Hi, I will look, into updating the documentation, I should probably add  `...` behind the MIN as there are a bunch of different models (all supported, as they are from the MIN family)
