### ISSUE TITLE
Versioning gone wrong

### ISSUE THREAD

**Issue by Maes152** [egguy/grott-home-assistant-add-on#79]
I've been using this addon for a while. I just noticed a new update came out in January.
This update is not coming through in Home Assistant. 

Closer inspection shows that the addon is now available twice in the store. The one I've installed is 0.1.5 and the other one that has popped up is the newer 0.1.6.

Am I supposed to uninstall the current addon and move to the other? I'm afraid I'll lose history data and such if I do. 

![image](https://github.com/egguy/grott-home-assistant-add-on/assets/59172270/519a4329-8f13-4a38-97d9-9d6fb4cd8fab)

**Comment by egguy** [comment]
Hi, 
I'm going to alter the naming and the versioning to have the old repo more in line with the new repo.

If I'm not mistaken how HA works, you can swap the 2 add-ons. The devices will be the same, so won't loose data (Still a good idea to do a HA backup before).

The old add-on will be removed in the next few months, I'm going to add a message to suggest the migration.

Thanks for your original add-on @Maes152, It is the base of these one.
