### ISSUE TITLE
New router, new ip

### ISSUE THREAD

**Issue by JacekJI** [egguy/grott-home-assistant-add-on#81]
Hello,

Addon worked fine but I changed my router and all IPs 

Growatt doesnt work anymore on home assistant

What I should do?
![inbound7076562788557641608](https://github.com/egguy/grott-home-assistant-add-on/assets/120251550/47e59c07-207d-46db-b6e6-24a687e0c19d)
![inbound576438154483996117](https://github.com/egguy/grott-home-assistant-add-on/assets/120251550/f048f6da-a81f-421e-82bf-24c4da52e3f7)

**Comment by egguy** [comment]
Hi,

You need to find the new IP of Home Assistant, after this you need to reconfigure your stick to send the data to the new HA ip. The grott in the addon is not affected by the IP change.
