### ISSUE TITLE
suddenly stopped sending mqtt data via ha_plugin

### ISSUE THREAD

**Issue by f0m3** [egguy/grott-home-assistant-add-on#84]
Hi, 
the addon suddenly stopped to send mqtt data via the plugin. I didnt change anything intentionally.
there is just no mqtt update to mosquitto anymore.
I tried to reinstall, checked if the user "addons" exists and so on...
The proxy mode seems to work because the growatt server gets updated and only updated when the add-on is running.

Here is my config:
`data_path: /config/grott
gmode: proxy
grott_mqtt: false
ginvtype: default
ginvtypemap: "{\"SPE*******\":\"SPH\", \"FVJ*****\":\"default\"}"
retain: false
verbose: true
ha_plugin: true
mqtt: {}
gnomqtt: false`

and this is the log:
`-----------------------------------------------------------
 Add-on: Grott Beta branch (2.8)
 The Growatt inverter monitor with current HA plugin integrated
-----------------------------------------------------------
 Add-on version: 0.1.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.7.2
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[10:26:12] INFO: Preparing to start...
`
[..]
`

T06NNNNXMIN  : 
{'decrypt': {'value': 'true'}, 'pvserial': {'value': 76, 'length': 10, 'type': 'text', 'divide': 10}, 'date': {'value': 136, 'divide': 10}, 'group1start': {'value': 150, 'length': 2, 'type': 'num', 'incl': 'no'}, 'group1end': {'value': 154, 'length': 2, 'type': 'num', 'incl': 'no'}, 'pvstatus': {'value': 158, 'length': 2, 'type': 'num', 'divide': 1}, 'pvpowerin': {'value': 162, 'length': 4, 'type': 'num', 'divide': 10}, 'pv1voltage': {'value': 170, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1current': {'value': 174, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1watt': {'value': 178, 'length': 4, 'type': 'num', 'divide': 10}, 'pv2voltage': {'value': 186, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2current': {'value': 190, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2watt': {'value': 194, 'length': 4, 'type': 'num', 'divide': 10}, 'pv3voltage': {'value': 202, 'length': 2, 'type': 'num', 'divide': 10}, 'pv3current': {'value': 206, 'length': 2, 'type': 'num', 'divide': 10}, 'pv3watt': {'value': 210, 'length': 4, 'type': 'num', 'divide': 10}, 'pv4voltage': {'value': 218, 'length': 2, 'type': 'num', 'divide': 10}, 'pv4current': {'value': 222, 'length': 2, 'type': 'num', 'divide': 10}, 'pv4watt': {'value': 226, 'length': 4, 'type': 'num', 'divide': 10}, 'pvpowerout': {'value': 250, 'length': 4, 'type': 'num', 'divide': 10}, 'pvfrequentie': {'value': 258, 'length': 2, 'type': 'num', 'divide': 100}, 'pvgridvoltage': {'value': 262, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent': {'value': 266, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower': {'value': 270, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage2': {'value': 278, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent2': {'value': 282, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower2': {'value': 286, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage3': {'value': 294, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent3': {'value': 298, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower3': {'value': 302, 'length': 4, 'type': 'num', 'divide': 10}, 'vacrs': {'value': 310, 'length': 2, 'type': 'num', 'divide': 10}, 'vacst': {'value': 314, 'length': 2, 'type': 'num', 'divide': 10}, 'vactr': {'value': 318, 'length': 2, 'type': 'num', 'divide': 10}, 'ptousertotal': {'value': 322, 'length': 4, 'type': 'num', 'divide': 10}, 'ptogridtotal': {'value': 330, 'length': 4, 'type': 'num', 'divide': 10}, 'ptoloadtotal': {'value': 338, 'length': 4, 'type': 'num', 'divide': 10}, 'totworktime': {'value': 346, 'length': 4, 'type': 'num', 'divide': 7200}, 'pvenergytoday': {'value': 354, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytotal': {'value': 362, 'length': 4, 'type': 'num', 'divide': 10}, 'epvtotal ': {'value': 370, 'length': 4, 'type': 'num', 'divide': 10}, 'epv1today ': {'value': 378, 'length': 4, 'type': 'num', 'divide': 10}, 'epv1total': {'value': 386, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2today': {'value': 394, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2total': {'value': 402, 'length': 4, 'type': 'num', 'divide': 10}, 'epv3today': {'value': 410, 'length': 4, 'type': 'num', 'divide': 10}, 'epv3total': {'value': 418, 'length': 4, 'type': 'num', 'divide': 10}, 'etousertoday': {'value': 426, 'length': 4, 'type': 'num', 'divide': 10}, 'etousertotal': {'value': 434, 'length': 4, 'type': 'num', 'divide': 10}, 'etogridtoday': {'value': 442, 'length': 4, 'type': 'num', 'divide': 10}, 'etogridtotal': {'value': 450, 'length': 4, 'type': 'num', 'divide': 10}, 'eloadtoday': {'value': 458, 'length': 4, 'type': 'num', 'divide': 10}, 'eloadtotal': {'value': 466, 'length': 4, 'type': 'num', 'divide': 10}, 'deratingmode': {'value': 502, 'length': 2, 'type': 'num', 'divide': 1}, 'iso': {'value': 506, 'length': 2, 'type': 'num', 'divide': 1}, 'dcir': {'value': 510, 'length': 2, 'type': 'num', 'divide': 10}, 'dcis': {'value': 514, 'length': 2, 'type': 'num', 'divide': 10}, 'dcit': {'value': 518, 'length': 2, 'type': 'num', 'divide': 10}, 'gfci': {'value': 522, 'length': 4, 'type': 'num', 'divide': 1}, 'pvtemperature': {'value': 530, 'length': 2, 'type': 'num', 'divide': 10}, 'pvipmtemperature': {'value': 534, 'length': 2, 'type': 'num', 'divide': 10}, 'temp3': {'value': 538, 'length': 2, 'type': 'num', 'divide': 10}, 'temp4': {'value': 542, 'length': 2, 'type': 'num', 'divide': 10}, 'temp5': {'value': 546, 'length': 2, 'type': 'num', 'divide': 10}, 'pbusvoltage': {'value': 550, 'length': 2, 'type': 'num', 'divide': 10}, 'nbusvoltage': {'value': 554, 'length': 2, 'type': 'num', 'divide': 10}, 'ipf': {'value': 558, 'length': 2, 'type': 'num', 'divide': 1}, 'realoppercent': {'value': 562, 'length': 2, 'type': 'num', 'divide': 1}, 'opfullwatt': {'value': 566, 'length': 4, 'type': 'num', 'divide': 10}, 'standbyflag': {'value': 574, 'length': 2, 'type': 'num', 'divide': 1}, 'faultcode': {'value': 578, 'length': 2, 'type': 'num', 'divide': 1}, 'warningcode': {'value': 582, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword0': {'value': 586, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword1': {'value': 590, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword2': {'value': 594, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword3': {'value': 598, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword4': {'value': 602, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword5': {'value': 606, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword6': {'value': 610, 'length': 2, 'type': 'num', 'divide': 1}, 'systemfaultword7': {'value': 614, 'length': 2, 'type': 'num', 'divide': 1}, 'invstartdelaytime': {'value': 618, 'length': 2, 'type': 'num', 'divide': 1}, 'bdconoffstate': {'value': 630, 'length': 2, 'type': 'num', 'divide': 1}, 'drycontactstate': {'value': 634, 'length': 2, 'type': 'num', 'divide': 1}, 'group2start': {'value': 658, 'length': 2, 'type': 'num', 'incl': 'no'}, 'group2end': {'value': 662, 'length': 2, 'type': 'num', 'incl': 'no'}, 'edischrtoday': {'value': 666, 'length': 4, 'type': 'num', 'divide': 10}, 'edischrtotal': {'value': 674, 'length': 4, 'type': 'num', 'divide': 10}, 'echrtoday': {'value': 682, 'length': 4, 'type': 'num', 'divide': 10}, 'echrtotal': {'value': 690, 'length': 4, 'type': 'num', 'divide': 10}, 'eacchrtoday': {'value': 698, 'length': 4, 'type': 'num', 'divide': 10}, 'eacchrtotal': {'value': 706, 'length': 4, 'type': 'num', 'divide': 10}, 'priority': {'value': 742, 'length': 2, 'type': 'num', 'divide': 1}, 'epsfac': {'value': 746, 'length': 2, 'type': 'num', 'divide': 100}, 'epsvac1': {'value': 750, 'length': 2, 'type': 'num', 'divide': 10}, 'epsiac1': {'value': 754, 'length': 2, 'type': 'num', 'divide': 10}, 'epspac1': {'value': 758, 'length': 4, 'type': 'num', 'divide': 10}, 'epsvac2': {'value': 766, 'length': 2, 'type': 'num', 'divide': 10}, 'epsiac2': {'value': 770, 'length': 2, 'type': 'num', 'divide': 10}, 'epspac2': {'value': 774, 'length': 4, 'type': 'num', 'divide': 10}, 'epsvac3': {'value': 782, 'length': 2, 'type': 'num', 'divide': 10}, 'epsiac3': {'value': 786, 'length': 2, 'type': 'num', 'divide': 10}, 'epspac3': {'value': 790, 'length': 4, 'type': 'num', 'divide': 10}, 'epspac': {'value': 798, 'length': 4, 'type': 'num', 'divide': 10}, 'loadpercent': {'value': 806, 'length': 2, 'type': 'num', 'divide': 10}, 'pf': {'value': 810, 'length': 2, 'type': 'num', 'divide': 10}, 'dcv': {'value': 814, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc1_sysstatemode': {'value': 830, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc1_faultcode': {'value': 834, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc1_warncode': {'value': 838, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc1_vbat': {'value': 842, 'length': 2, 'type': 'num', 'divide': 100}, 'bdc1_ibat': {'value': 846, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc1_soc': {'value': 850, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc1_vbus1': {'value': 854, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc1_vbus2': {'value': 858, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc1_ibb': {'value': 862, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc1_illc': {'value': 866, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc1_tempa': {'value': 870, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc1_tempb': {'value': 874, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc1_pdischr': {'value': 878, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc1_pchr': {'value': 886, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc1_edischrtotal': {'value': 894, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc1_echrtotal': {'value': 902, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc1_flag': {'value': 914, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc2_sysstatemode': {'value': 922, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc2_faultcode': {'value': 926, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc2_warncode': {'value': 930, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc2_vbat': {'value': 934, 'length': 2, 'type': 'num', 'divide': 100}, 'bdc2_ibat': {'value': 938, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc2_soc': {'value': 942, 'length': 2, 'type': 'num', 'divide': 1}, 'bdc2_vbus1': {'value': 946, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc2_vbus2': {'value': 950, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc2_ibb': {'value': 954, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc2_illc': {'value': 958, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc2_tempa': {'value': 962, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc2_tempb': {'value': 966, 'length': 2, 'type': 'num', 'divide': 10}, 'bdc2_pdischr': {'value': 970, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc2_pchr': {'value': 978, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc2_edischrtotal': {'value': 986, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc2_echrtotal': {'value': 994, 'length': 4, 'type': 'num', 'divide': 10}, 'bdc2_flag': {'value': 1006, 'length': 4, 'type': 'num', 'divide': 1}, 'bms_status': {'value': 1014, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_error': {'value': 1018, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_warninfo': {'value': 1022, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_soc': {'value': 1026, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_batteryvolt': {'value': 1030, 'length': 2, 'type': 'num', 'divide': 100}, 'bms_batterycurr': {'value': 1034, 'length': 2, 'type': 'num', 'divide': 100}, 'bms_batterytemp': {'value': 1038, 'length': 2, 'type': 'num', 'divide': 10}, 'bms_maxcurr': {'value': 1042, 'length': 2, 'type': 'num', 'divide': 100}, 'bms_deltavolt': {'value': 1046, 'length': 2, 'type': 'num', 'divide': 100}, 'bms_cyclecnt': {'value': 1050, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_soh': {'value': 1054, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_constantvolt': {'value': 1058, 'length': 2, 'type': 'num', 'divide': 100}, 'bms_bms_info': {'value': 1062, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_packinfo': {'value': 1066, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_usingcap': {'value': 1070, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_fw': {'value': 1074, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_mcuversion': {'value': 1078, 'length': 2, 'type': 'num', 'divide': 1}, 'bms_commtype': {'value': 1082, 'length': 2, 'type': 'num', 'divide': 1}}

Grott external record whitelist 'recwl.txt' not found

Grott records whitelisted :  {'5116', '5219', '5104', '5050', '5216', '5003', '0120', '0116', '5105', '5019', '0119', '0104', '5119', '5250', '5005', '0103', '5229', '0105', '501b', '5129', '5150', '0150', '5016', '5103', '5004'}

Grott settings:

_Generic:
	version:             	 2.8.2
	verbose:             	 True
	trace:               	 False
	config file:         	 /config/grott/grott.ini
	minrecl:             	 100
	decrypt:             	 True
	compat:              	 False
	invtype:             	 default
	invtypemap:          	 {'SPE****': 'SPH', 'FVJ****': 'default'}
	include_all:         	 False
	blockcmd:            	 False
	noipf:               	 False
	time:                	 auto
	sendbuf:             	 True
	timezone:            	 local
	valueoffset:         	 6
	offset:              	 6
	inverterid:          	 automatic
	mode:                	 proxy
	grottip              	 default
	grottport            	 5279
_MQTT:
	nomqtt               	 True
	mqttip:              	 192.168.1.106
	mqttport:            	 1883
	mqtttopic:           	 energy/growatt
	mqttmtopic:          	 False
	mqttmtopicname:      	 energy/meter
	mqttinverterintopic: 	 False
	mqtttretain:         	 False
	mqtttauth:           	 True
	mqttuser:            	 mqttuser
	mqttpsw:             	 **secret**
_Growatt server:
	growattip:           	 47.91.67.66
	growattport:         	 5279
_PVOutput:
	pvoutput:            	 False
	pvdisv1:             	 False
	pvtemp:              	 False
	pvurl:               	 https://pvoutput.org/service/r2/addstatus.jsp
	pvapikey:            	 yourapikey
	pvinverters:         	 1
	pvsystemid:          	 systemid1
_Influxdb:
	influx:             	 False
	influx2:            	 False
	database:           	 grottdb
	ip:                 	 localhost
	port:               	 8086
	user:               	 grott
	password:           	 **secret**
	organization:       	 grottorg
	bucket:             	 grottdb
	token:              	 **secret**
_Extension:
	extension:          	 True
	extname:            	 grottext.ha
	extvar:             	 {'ha_mqtt_host': 'core-mosquitto', 'ha_mqtt_port': '1883', 'ha_mqtt_user': 'addons', 'ha_mqtt_password': 'imooroGh2giijaiToo6moopuwaqu1ohsh7Thah9eiWeiNg9tuiMoo9yia7aey0Ai', 'ha_mqtt_retain': False}

Grott proxy mode started
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Hostname : 8ce4abae-grott-current
IP :  172.30.33.6 , port :  5279 `

**Comment by egguy** [comment]
If you are getting data in growatt website but not grott it is highly possible you are affected by the growatt stick reset problem

Could you please try this : https://github.com/egguy/addon-grott-beta/issues/51#issuecomment-2231910621

**Comment by rhpijnacker** [comment]
I had exactly this problem yesterday. My ShineLink-LAN stick had defaulted back to server.growatt.com and I had to reconfigure it to send the data to my local grott server.

**Comment by f0m3** [comment]
Thank you so much. That ofc. solved the problem.
Thanks for the work - enjoy the coffee!

**Comment by f0m3** [comment]
Not sure if this is interesting for you:
I resetted the wifisticks ip to my local grott. It worked immidately. But just for one dataset. It was automatically reset again to growatts server.
I tried it now with gblockcmd: true before i reset the shine stick..

Lets see what happens...
